### ISSUE TITLE
[ Feature ] Enter on keyboard inserts a new line 

### ISSUE THREAD

**Issue by MalikKillian** [UnknownEnergy/chatgpt-api#10]
Current behavior is for the prompt to be submitted when I hit enter on my phone keyboard. I would like to have an option (or make it default) for the keyboard to enter a new line instead. This will help with sending code snippets in the prompt as you may normally do with chat GPT in the browser.

**Comment by UnknownEnergy** [comment]
interesting that does not happen on my Android phone when I use the Android app. Which phone, model & operating system do you use? Maybe try another keyboard for your phone which does not hit "enter".
"Enter" is needed for PC as it makes typing and sending faster and shift+enter will be newline, but as said on my phone it does not send it directly via the Android keyboard.

**Comment by UnknownEnergy** [comment]
will close this ticket now as there was no response so far, so I guess the issue is solved. If it still happens please let us know

**Comment by MalikKillian** [comment]
Sorry, I had forgotten I added this report (and hoped my behavior was the common behavior).

I tried the latest version of Gboard (12.8.12.514733254-release-arm64-v8a) and my phone's built-in Samsung Keyboard (5.4.85.3) and both submit when I hit the enter key.

Phone model: Galaxy S10e
Phone model number: SM-G970U
Android ver: 12
