### ISSUE TITLE
"The model 'gpt-4' does not exist" when trying to use it

### ISSUE THREAD

**Issue by maximilianschlipf** [UnknownEnergy/chatgpt-api#12]
Hi, I just started to using your client. When trying to use gpt-4 I get a browser alert, telling me that the model gpt-4 does not exist:
![Bildschirmfoto 2023-04-20 um 10 07 24](https://user-images.githubusercontent.com/45205735/233301749-cc9944ff-b55b-4e15-bdb5-518762f70e49.png)

This does not seem to be specific to this client as I encountered it when using the following client as well: https://github.com/ShipBit/slickgpt

**Comment by maximilianschlipf** [comment]
oh my bad, my key wasn't working with gpt-4

**Comment by UnknownEnergy** [comment]
ah yes it is an issue at the OpenAI Api they return model gpt-4 does not exist, but it does you just need access to it via your account.
