### ISSUE TITLE
Control completely with voice upon opening app, text-to-speech results as well

### ISSUE THREAD

**Issue by notmyHubG** [UnknownEnergy/chatgpt-api#13]
I'd love to have chatgpt in my ear all day. I know its not too hard to open a chat and be able to talk to speech a question and have the result read aloud to you. Just too busy to contribute. :/

**Comment by UnknownEnergy** [comment]
That would be a cool feature yes but that is currently not easily doable as OpenAI does not offer a Text-to-Talk model. Maybe the do in the future or we plan on using also other models from other companies which would allow us to do it. So this feature can take longer and is not planed now, as there is no easy possibility. If you know something else please let us know.

**Comment by UnknownEnergy** [comment]
@notmyHubG  quick update OpenAI released now Text to speech. Now you can use Chatworm with Speech have fun ;)
