### ISSUE TITLE
[Feature] Implement file upload

### ISSUE THREAD

**Issue by tioannidis** [UnknownEnergy/chatgpt-api#16]
Hi,
what do you think about the possibility to upload files (doc, pdf) so that ChatGPT can translate them, for example?
Regards,
Theo

**Comment by UnknownEnergy** [comment]
sounds like a good idea, I know that there are already some tools out there but with the newer models with more tokens it makes more sense to also include a feature like that yes

**Comment by UnknownEnergy** [comment]
At the moment it is not easily possible to create a fileupload as big files require some kind of memory to load it into.
Check this project out: https://github.com/pashpashpash/vault-ai
they made a tool specifically for file uploads. If OpenAI in the future supports direct file uploads via their endpoints we could do it easily but for now I would suggest to use the other tool.

regards,
Daniel

**Comment by tioannidis** [comment]
ok, thanks for the infos
