### ISSUE TITLE
can you add a place to fill in prompts?

### ISSUE THREAD

**Issue by noangel2014** [UnknownEnergy/chatgpt-api#4]
Hello, this tool is great, but I found that the model options seem to be unselectable. Also, can you add a place to fill in prompts?

**Comment by UnknownEnergy** [comment]
Hello the models are only visible when you add your api key. They are getting loaded from openai via your api key, alos you can fill in your prompt at the bottom of the page "Type a message"

**Comment by UnknownEnergy** [comment]
did that solve your issue? otherwise I am closing it

**Comment by UnknownEnergy** [comment]
closing the issue no response so far so I guess it is fixed. If the issue continuous please open another ticket
