### ISSUE TITLE
option to limit the requested messages

### ISSUE THREAD

**Issue by tioannidis** [UnknownEnergy/chatgpt-api#5]
Hi,
when I use your application to translate or rephrase lengthy texts, I encounter an error after a few translations:
`This model's maximum context length is 4097 tokens. However, you requested 5471 tokens (3471 in the messages, 2000 in the completion). Please reduce the length of the messages or completion.`

![image](https://user-images.githubusercontent.com/1592909/226159190-288942c9-15df-485e-ac36-e3fd30c661b6.png)

Apparently, with each request the complete chat history is sent. I understand that it is important for the context of the DIskusion, but after a while it comes to this problem. A parameter to set this manually(0-n) would be ideal, because for translations this is not necessary. 
Besides, the longer the request, the more expensive.

Regards,
Theo

**Comment by UnknownEnergy** [comment]
Hi,
you can change the model to text-davinic-003 which is not a chat completion model and is not sending the complete chat again for example. Also you can try to reduce the max_tokens if this helps then it should not happen quickly. gtp-3.5-turbo was made for chat completion. Also you can refresh the page as we do not have the option to create new chats and it should start from beginning again.
Does that help you?

Regards,
Daniel

**Comment by UnknownEnergy** [comment]
what i did change now is the default temperature to 0.7 and maxTokens to 256 which is now the same default as in the openai playground.

**Comment by tioannidis** [comment]
than you :-)
