### ISSUE TITLE
Used credit is no longer displayed

### ISSUE THREAD

**Issue by tioannidis** [UnknownEnergy/chatgpt-api#7]
as described in the title, the used credit is no longer displayed.
Best Regards,
Theo

![grafik](https://user-images.githubusercontent.com/1592909/229373468-45e3115f-baee-473a-b7d2-e8912711a4e7.png)

![grafik](https://user-images.githubusercontent.com/1592909/229373604-cb9aaf78-6521-4a0b-b4c7-55194ec2d4ab.png)

**Comment by UnknownEnergy** [comment]
Hello thank you for the info. At the moment we switched out the free trial usage by the actual number you pay.
The free trial is not displayed anymore as this is a separate function by OpenAI.

**Comment by UnknownEnergy** [comment]
also looks like OpenAI blocked now the access from other apps with the api key now some kind of session key is needed

**Comment by tioannidis** [comment]
ok thanks for the info

> also looks like OpenAI blocked now the access from other apps with the api key now some kind of session key is needed

But your app is still working. In which case is the session needed?

**Comment by UnknownEnergy** [comment]
Yes everything works as normal just the free credits is not working anymore as they now require some kind of session token. The actual tokens you pay for are still working as this is another endpoint.
