### ISSUE TITLE
Code error

### ISSUE THREAD

**Issue by oscar15977** [UnknownEnergy/chatgpt-api#8]
![d272595b606d6bcd9bc124acafd1226](https://user-images.githubusercontent.com/129292202/230000445-1ff70567-793c-4adc-8635-1594739b886d.png)

**Comment by UnknownEnergy** [comment]
can you try again now

**Comment by oscar15977** [comment]
Ok, that's all done now

**Comment by oscar15977** [comment]
![c886b2ca4c9f78691dba020ad1438f4](https://user-images.githubusercontent.com/129292202/230283234-5d8caa25-928b-4f78-a3a9-1035248dae3e.png)
After communicating with Chatgpt for some time, the program reported an error

**Comment by UnknownEnergy** [comment]
thats because the model can't use more text. You could use a newer model with a larger context size like GPT4 or refresh the page and start a new conversation or try to change the "Max Tokens" to lower it.

**Comment by oscar15977** [comment]
Refreshing the web doesn't help either, you need to know what the browser has stored

**Comment by oscar15977** [comment]
Refreshing the web doesn't work either, you have to clear the browser of the information stored there

**Comment by oscar15977** [comment]
Refreshing the web page didn't help; I needed to clear the browser's stored information before it could work properly

**Comment by UnknownEnergy** [comment]
interesting this issue is new to me nobody else has that. The conversation should not be cached inside the browser, the app itself is not doing that for sure. Could you try another browser or which browser are you using?

**Comment by UnknownEnergy** [comment]
I close the issue for now as there is no known bug in this areas, probably client issue.
If it persists keep reaching out again

**Comment by oscar15977** [comment]
![1681129211120](https://user-images.githubusercontent.com/129292202/230900459-dffa353e-c81f-44a2-91a5-d361f4533a20.jpg)
